#!/bin/sh

PROG=../perfumesh

if [ ! -f "setup.prfm" ]; then
	ln -s ../setup.prfm setup.prfm
fi

for f in [0-9]*.prfm; do
	b=`basename $f .prfm`
	echo -n test $f ": " `head -1 $f` ": "
	$PROG $f > tmp 2> /dev/null
#	valgrind $PROG $f > tmp
	diff ${b}.res tmp > tmp.diff
	if [ $? -ne 0 ]; then
		echo "NG"
	else
		echo "OK"
	fi
	cat tmp.diff
done

rm -f tmp tmp.diff
